name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
    
    - name: SSH to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: '54.169.103.244'
        username: ubuntu
        password: '123'
        script: |
          ls
          cd ./node-ci-cd
          git pull origin master
          npm run start:dev

    # - name: Install dependencies
    #   run: npm install

    # - name: Run start
    #   run: npm run start:dev

            


      
