name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix: 
        node-version: [19.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}

      - name: Pull code
        run: git pull origin master

      - name: start
        run: npm run start:dev



      
      # - name: Install dependencies
      #   run: npm install --force

      # - name: Start application
      #   run: npm run start:dev
      #   timeout-minutes: 1
            


      
